// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using RoomAvability;
using RoomAvability.Models;

namespace RoomAvability
{
    public static partial class RoomAvabilityOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the RoomAvability.IRoomAvabilityOperations.
        /// </param>
        public static IList<RoomAvabilityModel> Get(this IRoomAvabilityOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IRoomAvabilityOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the RoomAvability.IRoomAvabilityOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<RoomAvabilityModel>> GetAsync(this IRoomAvabilityOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<RoomAvability.Models.RoomAvabilityModel>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
