// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using RoomAvability.Models;

namespace RoomAvability.Models
{
    public static partial class RoomAvabilityModelCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<RoomAvabilityModel> DeserializeJson(JToken inputObject)
        {
            IList<RoomAvabilityModel> deserializedObject = new List<RoomAvabilityModel>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                RoomAvabilityModel roomAvabilityModel = new RoomAvabilityModel();
                roomAvabilityModel.DeserializeJson(iListValue);
                deserializedObject.Add(roomAvabilityModel);
            }
            return deserializedObject;
        }
    }
}
