// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace RoomAvability.Models
{
    public partial class RoomAvabilityModel
    {
        private DateTimeOffset? _endTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? EndTime
        {
            get { return this._endTime; }
            set { this._endTime = value; }
        }
        
        private string _freeBusyStatus;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FreeBusyStatus
        {
            get { return this._freeBusyStatus; }
            set { this._freeBusyStatus = value; }
        }
        
        private bool? _isMeeting;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsMeeting
        {
            get { return this._isMeeting; }
            set { this._isMeeting = value; }
        }
        
        private bool? _isPrivate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsPrivate
        {
            get { return this._isPrivate; }
            set { this._isPrivate = value; }
        }
        
        private string _location;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }
        
        private DateTimeOffset? _startTime;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? StartTime
        {
            get { return this._startTime; }
            set { this._startTime = value; }
        }
        
        private string _subject;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Subject
        {
            get { return this._subject; }
            set { this._subject = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RoomAvabilityModel class.
        /// </summary>
        public RoomAvabilityModel()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken endTimeValue = inputObject["EndTime"];
                if (endTimeValue != null && endTimeValue.Type != JTokenType.Null)
                {
                    this.EndTime = ((DateTimeOffset)endTimeValue);
                }
                JToken freeBusyStatusValue = inputObject["FreeBusyStatus"];
                if (freeBusyStatusValue != null && freeBusyStatusValue.Type != JTokenType.Null)
                {
                    this.FreeBusyStatus = ((string)freeBusyStatusValue);
                }
                JToken isMeetingValue = inputObject["IsMeeting"];
                if (isMeetingValue != null && isMeetingValue.Type != JTokenType.Null)
                {
                    this.IsMeeting = ((bool)isMeetingValue);
                }
                JToken isPrivateValue = inputObject["IsPrivate"];
                if (isPrivateValue != null && isPrivateValue.Type != JTokenType.Null)
                {
                    this.IsPrivate = ((bool)isPrivateValue);
                }
                JToken locationValue = inputObject["Location"];
                if (locationValue != null && locationValue.Type != JTokenType.Null)
                {
                    this.Location = ((string)locationValue);
                }
                JToken startTimeValue = inputObject["StartTime"];
                if (startTimeValue != null && startTimeValue.Type != JTokenType.Null)
                {
                    this.StartTime = ((DateTimeOffset)startTimeValue);
                }
                JToken subjectValue = inputObject["Subject"];
                if (subjectValue != null && subjectValue.Type != JTokenType.Null)
                {
                    this.Subject = ((string)subjectValue);
                }
            }
        }
    }
}
